export const projects = [
  {
    title: 'Groupomania',
    description: "Projet n°7, faisant partie de la formation OpenClassRooms. Créer un réseau social d'entreprise, en réalisant la partie BackEnd et FrontEnd.",
    image: '/images/Groupomania.png',
    tags: ['MySql', 'Express', 'React', 'Node'],
    source: 'https://github.com/Lokki68/libertbrice_p7_01012022',
    visit: '',
    id: 0,
  },
  {
    title: 'Blog Kyoto',
    description: "Blog fictif d'une agence de voyage sur la ville de Kyoto. Projet réalisé lors de la formation de développeur FrontEnd sur Udemy",
    image: '/images/blog-kyoto.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/Lokki68/kyotoBlog',
    visit: 'https://lokki68.github.io/kyotoBlog/',
    id: 1,
  },
  {
    title: 'Blog React',
    description: "Blog fictif, réalisé lors de la formation de développeur ReactJs sur Udemy",
    image: '/images/Blog-React-min.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/Lokki68/blog-react',
    visit: 'https://lokki68.github.io/blog-react/',
    id: 2,
  },
  {
    title: 'OhMyFood',
    description: "Projet n°3 de la formation OpenClassRooms. Ce projet est la création d'une application pour réserver un commander un menu complet dans le restaurant de son choix. Nous devions réaliser ce MVP, en y incluant quelques animations au survol, nous devions utiliser Sass pour réaliser la partie visuelle de ce site.",
    image: '/images/OhMyFood.png',
    tags: ['Html', 'Sass'],
    source: 'https://github.com/Lokki68/LibertBrice_3_15052021',
    visit: 'https://lokki68.github.io/LibertBrice_3_15052021/',
    id: 3,
  },
  {
    title: 'Pokedex',
    description: "Pokédex réalisé lors de la formation de développeur Angular sur Udemy",
    image: '/images/Pokédex-min.png',
    tags: ['Angular', 'TypeScript'],
    source: 'https://github.com/Lokki68/pokemonAngular',
    visit: '',
    id: 4,
  },
  {
    title: 'Reservia',
    description: "Projet n°2 de la formation OpenClassRooms. Pour ce premier vrai projet et également le premier gros palier de la formation. Nous devions réaliser un site static pour une agence de location d'appartement pour les vacances.",
    image: '/images/Reservia.png',
    tags: ['Html', 'Css'],
    source: 'https://github.com/Lokki68/LibertBrice_2_30042021',
    visit: 'https://lokki68.github.io/LibertBrice_2_30042021/',
    id: 5,
  },
  {
    title: 'StackOverFlou',
    description: "Project perso guidé, réalisé avec le groupe Modulo-Tech",
    image: '/images/StackOverFlou.png',
    tags: ['ReactJs'],
    source: 'https://github.com/Lokki68/StackverFlou-Modulo',
    visit: '',
    id: 6,
  },
];

export const TimeLineData = [
  {year: 2017, text: 'Started my journey',},
  {year: 2018, text: 'Worked as a freelance developer',},
  {year: 2019, text: 'Founded JavaScript Mastery',},
  {year: 2020, text: 'Shared my projects with the world',},
  {year: 2021, text: 'Started my own platform',},
];
